### ISSUE TITLE
No module named 'Rumps' ?

### ISSUE THREAD

**Issue by steveharman** [mdbraber/radiobar#5]
HI,

When using `python setup.py py2app` I'm getting the following error:

```
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    setup(
  File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/site-packages/py2app/build_app.py", line 907, in run
    self._run()
  File "/usr/local/lib/python3.8/site-packages/py2app/build_app.py", line 1125, in _run
    self.run_normal()
  File "/usr/local/lib/python3.8/site-packages/py2app/build_app.py", line 1237, in run_normal
    pkgdirs = self.collect_packagedirs()
  File "/usr/local/lib/python3.8/site-packages/py2app/build_app.py", line 1201, in collect_packagedirs
    [
  File "/usr/local/lib/python3.8/site-packages/py2app/build_app.py", line 1202, in <listcomp>
    os.path.join(os.path.realpath(self.get_bootstrap(pkg)), "")
  File "/usr/local/lib/python3.8/site-packages/py2app/build_app.py", line 2043, in get_bootstrap
    bootstrap = imp_find_module(bootstrap)[1]
  File "/usr/local/lib/python3.8/site-packages/modulegraph/util.py", line 33, in imp_find_module
    result = imp.find_module(name, path)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'rumps'
```

- macOS 10.15.6
- python 3.8.5 via brew

Is "ImportError: No module named 'rumps'" relevant?

Thanks,

Steve

**Comment by Am0rphous** [comment]
I experience similar problem @steveharman. It seems rumps, which stands for _Ridiculously Uncomplicated macOS Python Statusbar apps_ requires Python 2.6+.
Someone correct me if I'm wrong, but I think the project has to be ported to a newer Python version and files and packages has to be updated. I tried Python 2.7 and 3.10 on Kali Linux, and tried Python3 (3.9.13) on MacOS without success..

I also tried building it with Python 2.7 but get these errors (`python2.7 setup.py py2app`):
````
WARNING: The wheel package is not available.
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    setup_requires=['py2app'],
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/setuptools/__init__.py", line 145, in setup
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/setuptools/dist.py", line 448, in __init__
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/setuptools/dist.py", line 739, in finalize_options
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/setuptools/dist.py", line 738, in <lambda>
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2443, in load
  File "/usr/share/cffi-wheels/setuptools-44.1.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2449, in resolve
  File "/home/henrik/gitHub/radiobar/.eggs/py2app-0.28.2-py2.7.egg/py2app/build_app.py", line 23, in <module>
    import macholib.dyld
ImportError: No module named macholib.dyld
````

Btw check [this](https://github.com/exelban/custer) github repo out.
